
CREATE BIGFILE TABLESPACE bigtbs
 DATAFILE 'C:/Users/BASILIO.SALDARRIAGA/Desktop/Basilio Saldarriaga/Base datos avanzada/bigtbs.dbf' SIZE 50M;


 CREATE TEMPORARY TABLESPACE lmtemp
 TEMPFILE 'C:/Users/BASILIO.SALDARRIAGA/Desktop/Basilio Saldarriaga/Base datos avanzada/lmtemp.dbf'
 SIZE 20M REUSE
 EXTENT MANAGEMENT LOCAL UNIFORM SIZE 16M;
 
 
 ALTER TABLESPACE users OFFLINE NORMAL;
 ALTER TABLESPACE users ONLINE;



ALTER TABLESPACE BASILIO READ ONLY;

ALTER TABLESPACE bigtbs RENAME TO usersts;


DROP TABLESPACE UNDOTS01 INCLUDING CONTENTS;

CREATE UNDO TABLESPACE UNDOTS02
 DATAFILE 'C:/Users/BASILIO.SALDARRIAGA/Desktop/Basilio Saldarriaga/Base datos avanzada/undo02.dbf' SIZE 10M;


select * from dba_tablespaces;
select * from dba_data_files;
select * from user_users;

CREATE  TABLESPACE ALEXANDER
DATAFILE 'C:/Users/BASILIO.SALDARRIAGA/Desktop/Basilio Saldarriaga/Base datos avanzada/ALEX.dbf' SIZE 10M;


CREATE USER ALEX
IDENTIFIED BY ALEX99
DEFAULT TABLESPACE BASILIO
QUOTA ON 10M ON BASILIO;




CREATE SEQUENCE agencies_seq
START WITH 500
INCREMENT BY 2
NOCYCLE;

SELECT agencies_seq.CURRVAL FROM DUAL;

SELECT agencies_seq.NEXTVAL FROM DUAL;

CREATE TABLE PRUEBA(
ID INTEGER PRIMARY KEY,
VALOR VARCHAR2(255)
);

INSERT INTO PRUEBA VALUES (agencies_seq.NEXTVAL, 'Andres');

INSERT INTO PRUEBA VALUES (agencies_seq.NEXTVAL, 'Basilio');


SELECT * FROM PRUEBA;







